#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "formbricks"
name = "Formbricks"
description.en = "Survey Platform"
description.fr = "Plateforme d'enquête"

version = "5.1.4~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0-only"
website = "https://formbricks.com/"
admindoc = "https://formbricks.com/docs/developer-docs/contributing/get-started#local-machine-setup"
code = "https://github.com/formbricks/formbricks"

[integration]
yunohost = ">= 12.1.40"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/formbricks/formbricks/archive/refs/tags/5.1.4.tar.gz"
    sha256 = "bc112f2a95edf06c440a68459f434012aa989e8fd8f702887a178323667dad10"
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]
    allow_email = true
    
    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default=3000
    cubejs.default=4000

    [resources.apt]
    packages = [
        "postgresql",
        "redis-server"
    ]
    packages_from_raw_bash = """
        if [[ $YNH_DEBIAN_VERSION == "trixie" ]]; then
            echo "postgresql-17-pgvector";
        fi
    """

    [resources.apt.extras.postgresql]
    repo = "deb https://apt.postgresql.org/pub/repos/apt __YNH_DEBIAN_VERSION__-pgdg main"
    key = "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    packages_from_raw_bash = """
        if [[ $YNH_DEBIAN_VERSION == "bookworm" ]]; then
            echo "postgresql-15-pgvector";
        else echo "";
        fi
    """

    [resources.database]
    type = "postgresql"

    [resources.nodejs]
    version = "24"
