#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

encryption_key=$(ynh_string_random --length=32)
nextauth_secret=$(ynh_string_random --length=32)
cron_secret=$(ynh_string_random --length=32)
cubejs_api_secret=$(ynh_string_random --length=32)

ynh_app_setting_set --key=encryption_key --value=$encryption_key
ynh_app_setting_set --key=nextauth_secret --value=$nextauth_secret
ynh_app_setting_set --key=cron_secret --value=$cron_secret
ynh_app_setting_set --key=cubejs_api_secret --value=$cubejs_api_secret

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

#PNPM_VERSION=$(sed -n 's/.*"packageManager":\s*"pnpm@\([^"]*\)".*/\1/p' $install_dir/package.json)
#ynh_hide_warnings corepack enable && corepack prepare pnpm@${PNPM_VERSION} --activate
ynh_hide_warnings corepack enable && corepack prepare pnpm@11.7.0 --activate

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Survey Platform" --log="/var/log/$app/$app.log"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# INSTALL FORMBRICKS
#=================================================
ynh_script_progression "Installing $app..."

pushd $install_dir
    ynh_psql_db_shell <<< "CREATE EXTENSION IF NOT EXISTS vector;"
    ynh_exec_as_app pnpm install
    ynh_exec_as_app NODE_OPTIONS="--max_old_space_size=8192" TURBO_TELEMETRY_DISABLED=1 pnpm build
    ynh_exec_as_app TURBO_TELEMETRY_DISABLED=1 pnpm turbo run db:setup
popd

chown -R "$app:$app" "$install_dir"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
