#!/bin/bash

source /usr/share/yunohost/helpers

encryption_key=$(ynh_app_setting_get --key=encryption_key)
nextauth_secret=$(ynh_app_setting_get --key=nextauth_secret)
cron_secret=$(ynh_app_setting_get --key=cron_secret)
cubejs_api_secret=$(ynh_app_setting_get --key=cubejs_api_secret)

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_hide_warnings corepack enable && corepack prepare pnpm@latest --activate

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep=".env"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Survey Platform" --log="/var/log/$app/$app.log"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
#ynh_script_progression "Updating $app's configuration files..."

#ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# INSTALL FORMBRICKS
#=================================================
ynh_script_progression "Installing the app..."

pushd $install_dir
    ynh_exec_as_app pnpm install
    ynh_exec_as_app NODE_OPTIONS="--max-old-size=8192" TURBO_TELEMETRY_DISABLED=1 pnpm build
    ynh_exec_as_app TURBO_TELEMETRY_DISABLED=1 pnpm turbo run db:setup
popd

chown -R "$app:$app" "$install_dir"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
